version: "3.8"
services:
  user-mysql-db:
    image: mysql:8.0
    container_name: user-mysql-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: user123
      MYSQL_DATABASE: user_db
    networks:
      - user-network

  user-service:
    build: .
    container_name: user-service
    depends_on:
      - user-mysql-db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/userdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user123
    networks:
      - user-network

networks:
  user-network:
